---
hero_image: images/banner.png
theme: red
duration: 1
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Tightrope
description: Tilt your Sense HAT to guide a character along a path.
original_url: https://codeclubprojects.org/en-GB/sense-hat/tightrope
interests: ''
technologies: sense-hat
site_areas: codeclub, sense-hat
steps:
- title: 'Challenge: Create your own path'
- title: 'Challenge: Moving up!'
- title: 'Challenge: Changing the difficulty'

