---
hero_image: images/tightrope.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: दोरखंड
description: एका मार्गावर एका पात्राचे मार्गदर्शन करण्यासाठी आपली Sense Hat तिरपी करा.
original_url: https://codeclubprojects.org/en-GB/sense-hat/tightrope
interests: games
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'परिचय'
  - 
    title: एक मार्ग आखा
  - 
    title: 'आव्हान: आपला स्वतःचा मार्ग तयार करा'
  - 
    title: तुमचा पात्र रेखाटा
  - 
    title: 'रोल, पिच आणि यॉ'
  - 
    title: पात्राला हलविणे
  - 
    title: 'आव्हान: वरती जा!'
  - 
    title: परत सुरवातीला जाणे
  - 
    title: 'आव्हान: अडचणीची पातळी बदलणे'
