---
hero_image: images/tightrope.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: حبل البهلوان
description: امالة إلى Sense HAT الخاص بك لتوجيه شخصية على طول الطريق.
original_url: https://codeclubprojects.org/en-GB/sense-hat/tightrope
interests: ألعاب
technologies: sense-hat
site_areas: codeclub, python
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'المقدمة'
  - 
    title: ارسم مسار
  - 
    title: 'التحدي: أنشئ المسار الخاص بك'
  - 
    title: ارسم لاعبك
  - 
    title: 'لفة، اعلى اسفل وانحراف'
  - 
    title: تحريك الشخصية
  - 
    title: 'التحدي: التحرك!'
  - 
    title: العودة إلى البداية
  - 
    title: 'التحدي: تغيير الصعوبة'
