---
hero_image: images/tightrope.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmation-1, phys-comp-0, fabrication-0, communauté-0
title: Tightrope
description: Tilt your Sense HAT to guide a character along a path.
original_url: https://codeclubprojects.org/en-GB/sense-hat/tightrope
interests: games
technologies: sense-hat
site_areas: projets
hardware: sense-hat
software: ''
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: 'Introduction'
  - 
    title: Draw a path
  - 
    title: 'Challenge: Create your own path'
  - 
    title: Draw your player
  - 
    title: 'Roll, pitch and yaw'
  - 
    title: Moving the character
  - 
    title: 'Challenge: Moving up!'
  - 
    title: Going back to the start
  - 
    title: 'Challenge: Changing the difficulty'
